steps:
# Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-southeast1-docker.pkg.dev/aotga-production/wms-aotga/aotga-wms-frontend:${TAG_NAME}
      - '--build-arg'
      - 'ENVIRONMENT=production'
      - .
# Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-southeast1-docker.pkg.dev/aotga-production/wms-aotga/aotga-wms-frontend:${TAG_NAME}
# Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'aotga-wms-frontend-production',
        '--image',
        'asia-southeast1-docker.pkg.dev/aotga-production/wms-aotga/aotga-wms-frontend:${TAG_NAME}',
        '--region',
        'asia-southeast1',
        --platform',
        'manage',
        '--port',
        '80',
        '--memory',
        '1Gi',
        '--allow-unauthenticated',
        '--min-instances',
        '0',
        '--max-instances',
        '3',
        ]
timeout: '1800s'
options:
  machineType: E2_HIGHCPU_32